/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiendaderopa;

import java.awt.Color;

/**
 *
 * @author Samuel-Josue
 */
public class VentanaMenuTienda extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenuTienda
     */
    public VentanaMenuTienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        agregarBtn = new javax.swing.JButton();
        menuTituloLabel = new javax.swing.JLabel();
        mostrarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        comprarBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        fondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo MenWear.png"))); // NOI18N
        logoLabel.setText("jLabel1");
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, 180));

        tituloLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloLabel.setText("Bienvenido a MenWear");
        getContentPane().add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        agregarBtn.setBackground(new java.awt.Color(51, 51, 51));
        agregarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        agregarBtn.setForeground(new java.awt.Color(204, 204, 204));
        agregarBtn.setText("Agregar al carrito");
        agregarBtn.setBorder(null);
        agregarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarBtnMouseExited(evt);
            }
        });
        getContentPane().add(agregarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 360, 40));

        menuTituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        menuTituloLabel.setText("Menu");
        getContentPane().add(menuTituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        mostrarBtn.setBackground(new java.awt.Color(51, 51, 51));
        mostrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mostrarBtn.setForeground(new java.awt.Color(204, 204, 204));
        mostrarBtn.setText("Mostrar carrito");
        mostrarBtn.setBorder(null);
        mostrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseExited(evt);
            }
        });
        getContentPane().add(mostrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 360, 40));

        eliminarBtn.setBackground(new java.awt.Color(52, 51, 51));
        eliminarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(204, 204, 204));
        eliminarBtn.setText("Eliminar del carrito");
        eliminarBtn.setBorder(null);
        eliminarBtn.setBorderPainted(false);
        eliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarBtnMouseExited(evt);
            }
        });
        getContentPane().add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 360, 40));

        comprarBtn.setBackground(new java.awt.Color(51, 51, 51));
        comprarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comprarBtn.setForeground(new java.awt.Color(204, 204, 204));
        comprarBtn.setText("Comprar");
        comprarBtn.setBorder(null);
        comprarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comprarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comprarBtnMouseExited(evt);
            }
        });
        getContentPane().add(comprarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 360, 40));

        salirBtn.setBackground(new java.awt.Color(51, 51, 51));
        salirBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salirBtn.setForeground(new java.awt.Color(204, 204, 204));
        salirBtn.setText("Salir");
        salirBtn.setBorder(null);
        salirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirBtnMouseExited(evt);
            }
        });
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 360, 40));

        fondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo gris.jpg"))); // NOI18N
        getContentPane().add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarBtnMouseEntered
        agregarBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_agregarBtnMouseEntered

    private void agregarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarBtnMouseExited
        agregarBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_agregarBtnMouseExited

    private void mostrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseEntered
        mostrarBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_mostrarBtnMouseEntered

    private void mostrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseExited
        mostrarBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_mostrarBtnMouseExited

    private void eliminarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnMouseEntered
        eliminarBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_eliminarBtnMouseEntered

    private void eliminarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnMouseExited
        eliminarBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_eliminarBtnMouseExited

    private void comprarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarBtnMouseEntered
        comprarBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_comprarBtnMouseEntered

    private void comprarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarBtnMouseExited
        comprarBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_comprarBtnMouseExited

    private void salirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseEntered
        salirBtn.setBackground(Color.decode("#7B0D0D"));
    }//GEN-LAST:event_salirBtnMouseEntered

    private void salirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseExited
        salirBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_salirBtnMouseExited

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.out.println("Gracias por visitarnos :D");
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBtn;
    private javax.swing.JButton comprarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel menuTituloLabel;
    private javax.swing.JButton mostrarBtn;
    private javax.swing.JButton salirBtn;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
