
package tiendaderopa;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel-Josue
 */
public class VentanaMenuTienda extends javax.swing.JFrame {

    public static ArrayList <Ropa> camisas = new ArrayList();
    public static ArrayList <Ropa> pantalones = new ArrayList();
    public static ArrayList <Ropa> gorras = new ArrayList();
    public static ArrayList <Ropa> sueteres = new ArrayList();
    public static ArrayList <Ropa> zapatos = new ArrayList();
    public static ArrayList <Ropa> calzonetas = new ArrayList();
    
    /**
     * Creates new form VentanaMenuTienda
     */
    public VentanaMenuTienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogoFrame = new javax.swing.JFrame();
        catalogoPanel = new javax.swing.JPanel();
        catalogoLabel = new javax.swing.JLabel();
        camisasCtlgBtn = new javax.swing.JButton();
        pantalonesCtlgBtn = new javax.swing.JButton();
        gorrasCtlgBtn = new javax.swing.JButton();
        sueteresCtlgBtn = new javax.swing.JButton();
        zapatosCtlgBtn = new javax.swing.JButton();
        calzonetasCtlgBtn = new javax.swing.JButton();
        atrasCtlgBtn = new javax.swing.JButton();
        fondoCtlgLabel = new javax.swing.JLabel();
        camisasCtlgFrame = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        camisasPanel = new javax.swing.JPanel();
        camisasLabel = new javax.swing.JLabel();
        atrasCmsasBtn = new javax.swing.JButton();
        camisaMngCrtaBtn = new javax.swing.JButton();
        camisaMngLrgBtn = new javax.swing.JButton();
        camisetaMngCrtaBtn = new javax.swing.JButton();
        camisetaMngLrgBtn = new javax.swing.JButton();
        fondoCmsasLabel = new javax.swing.JLabel();
        mstrrCarritoFrame = new javax.swing.JFrame();
        mstrrCrrtoFondoPanel = new javax.swing.JPanel();
        mstrrCrrtoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarCarritoTxtArea = new javax.swing.JTextArea();
        atrasMstrrCrrtoBtn = new javax.swing.JButton();
        fondoMstrrCrrtoLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        tituloLabel = new javax.swing.JLabel();
        catalogoBtn = new javax.swing.JButton();
        menuTituloLabel = new javax.swing.JLabel();
        mostrarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        comprarBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        fondoLabel = new javax.swing.JLabel();

        catalogoFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        catalogoPanel.setBackground(new java.awt.Color(51, 51, 51));

        catalogoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        catalogoLabel.setForeground(new java.awt.Color(204, 204, 204));
        catalogoLabel.setText("Catalogo");
        catalogoPanel.add(catalogoLabel);

        catalogoFrame.getContentPane().add(catalogoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 160, 50));

        camisasCtlgBtn.setBackground(new java.awt.Color(51, 51, 51));
        camisasCtlgBtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        camisasCtlgBtn.setForeground(new java.awt.Color(204, 204, 204));
        camisasCtlgBtn.setText("Camisas");
        camisasCtlgBtn.setBorder(null);
        camisasCtlgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                camisasCtlgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                camisasCtlgBtnMouseExited(evt);
            }
        });
        camisasCtlgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camisasCtlgBtnActionPerformed(evt);
            }
        });
        catalogoFrame.getContentPane().add(camisasCtlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, 40));

        pantalonesCtlgBtn.setBackground(new java.awt.Color(51, 51, 51));
        pantalonesCtlgBtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        pantalonesCtlgBtn.setForeground(new java.awt.Color(204, 204, 204));
        pantalonesCtlgBtn.setText("Pantalones");
        pantalonesCtlgBtn.setBorder(null);
        pantalonesCtlgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pantalonesCtlgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pantalonesCtlgBtnMouseExited(evt);
            }
        });
        catalogoFrame.getContentPane().add(pantalonesCtlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 40));

        gorrasCtlgBtn.setBackground(new java.awt.Color(51, 51, 51));
        gorrasCtlgBtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        gorrasCtlgBtn.setForeground(new java.awt.Color(204, 204, 204));
        gorrasCtlgBtn.setText("Gorras");
        gorrasCtlgBtn.setBorder(null);
        gorrasCtlgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gorrasCtlgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gorrasCtlgBtnMouseExited(evt);
            }
        });
        catalogoFrame.getContentPane().add(gorrasCtlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 40));

        sueteresCtlgBtn.setBackground(new java.awt.Color(51, 51, 51));
        sueteresCtlgBtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        sueteresCtlgBtn.setForeground(new java.awt.Color(204, 204, 204));
        sueteresCtlgBtn.setText("Sueteres");
        sueteresCtlgBtn.setBorder(null);
        sueteresCtlgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sueteresCtlgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sueteresCtlgBtnMouseExited(evt);
            }
        });
        catalogoFrame.getContentPane().add(sueteresCtlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 190, 40));

        zapatosCtlgBtn.setBackground(new java.awt.Color(51, 51, 51));
        zapatosCtlgBtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        zapatosCtlgBtn.setForeground(new java.awt.Color(204, 204, 204));
        zapatosCtlgBtn.setText("Zapatos");
        zapatosCtlgBtn.setBorder(null);
        zapatosCtlgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                zapatosCtlgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                zapatosCtlgBtnMouseExited(evt);
            }
        });
        catalogoFrame.getContentPane().add(zapatosCtlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 190, 40));

        calzonetasCtlgBtn.setBackground(new java.awt.Color(51, 51, 51));
        calzonetasCtlgBtn.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        calzonetasCtlgBtn.setForeground(new java.awt.Color(204, 204, 204));
        calzonetasCtlgBtn.setText("Calzonetas");
        calzonetasCtlgBtn.setBorder(null);
        calzonetasCtlgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calzonetasCtlgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calzonetasCtlgBtnMouseExited(evt);
            }
        });
        catalogoFrame.getContentPane().add(calzonetasCtlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 190, 40));

        atrasCtlgBtn.setBackground(new java.awt.Color(51, 51, 51));
        atrasCtlgBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atrasCtlgBtn.setForeground(new java.awt.Color(204, 204, 204));
        atrasCtlgBtn.setText("Atras");
        atrasCtlgBtn.setBorder(null);
        atrasCtlgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasCtlgBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasCtlgBtnMouseExited(evt);
            }
        });
        atrasCtlgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasCtlgBtnActionPerformed(evt);
            }
        });
        catalogoFrame.getContentPane().add(atrasCtlgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 70, 30));

        fondoCtlgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo gris.jpg"))); // NOI18N
        catalogoFrame.getContentPane().add(fondoCtlgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        camisasCtlgFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        camisasPanel.setBackground(new java.awt.Color(204, 204, 204));
        camisasPanel.setForeground(new java.awt.Color(204, 204, 204));
        camisasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        camisasLabel.setBackground(new java.awt.Color(51, 51, 51));
        camisasLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        camisasLabel.setForeground(new java.awt.Color(51, 51, 51));
        camisasLabel.setText("Camisas");
        camisasPanel.add(camisasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.add(camisasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 110, 50));

        atrasCmsasBtn.setBackground(new java.awt.Color(204, 204, 204));
        atrasCmsasBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atrasCmsasBtn.setForeground(new java.awt.Color(51, 51, 51));
        atrasCmsasBtn.setText("Atras");
        atrasCmsasBtn.setBorder(null);
        atrasCmsasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasCmsasBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasCmsasBtnMouseExited(evt);
            }
        });
        atrasCmsasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasCmsasBtnActionPerformed(evt);
            }
        });
        jPanel2.add(atrasCmsasBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 70, 30));

        camisaMngCrtaBtn.setBackground(new java.awt.Color(204, 204, 204));
        camisaMngCrtaBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        camisaMngCrtaBtn.setForeground(new java.awt.Color(51, 51, 51));
        camisaMngCrtaBtn.setText("Camisa manga corta");
        camisaMngCrtaBtn.setBorder(null);
        camisaMngCrtaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                camisaMngCrtaBtnActionPerformed(evt);
            }
        });
        jPanel2.add(camisaMngCrtaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 160, 30));

        camisaMngLrgBtn.setBackground(new java.awt.Color(204, 204, 204));
        camisaMngLrgBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        camisaMngLrgBtn.setForeground(new java.awt.Color(51, 51, 51));
        camisaMngLrgBtn.setText("Camisa manga larga");
        camisaMngLrgBtn.setBorder(null);
        jPanel2.add(camisaMngLrgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 160, 30));

        camisetaMngCrtaBtn.setBackground(new java.awt.Color(204, 204, 204));
        camisetaMngCrtaBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        camisetaMngCrtaBtn.setForeground(new java.awt.Color(51, 51, 51));
        camisetaMngCrtaBtn.setText("Camiseta manga corta");
        camisetaMngCrtaBtn.setBorder(null);
        jPanel2.add(camisetaMngCrtaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 180, 30));

        camisetaMngLrgBtn.setBackground(new java.awt.Color(204, 204, 204));
        camisetaMngLrgBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        camisetaMngLrgBtn.setForeground(new java.awt.Color(51, 51, 51));
        camisetaMngLrgBtn.setText("Camiseta manga larga");
        camisetaMngLrgBtn.setBorder(null);
        jPanel2.add(camisetaMngLrgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 180, 30));

        fondoCmsasLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo gris.jpg"))); // NOI18N
        jPanel2.add(fondoCmsasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        camisasCtlgFrame.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        mstrrCarritoFrame.setMaximumSize(new java.awt.Dimension(416, 498));
        mstrrCarritoFrame.setSize(new java.awt.Dimension(416, 498));
        mstrrCarritoFrame.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mstrrCrrtoFondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mstrrCrrtoPanel.setBackground(new java.awt.Color(51, 51, 51));
        mstrrCrrtoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Mostrar carrito");
        mstrrCrrtoPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        mstrrCrrtoFondoPanel.add(mstrrCrrtoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 190, 50));

        mostrarCarritoTxtArea.setBackground(new java.awt.Color(153, 153, 153));
        mostrarCarritoTxtArea.setColumns(20);
        mostrarCarritoTxtArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mostrarCarritoTxtArea.setForeground(new java.awt.Color(51, 51, 51));
        mostrarCarritoTxtArea.setRows(5);
        jScrollPane1.setViewportView(mostrarCarritoTxtArea);

        mstrrCrrtoFondoPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 350, 350));

        atrasMstrrCrrtoBtn.setBackground(new java.awt.Color(51, 51, 51));
        atrasMstrrCrrtoBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atrasMstrrCrrtoBtn.setForeground(new java.awt.Color(204, 204, 204));
        atrasMstrrCrrtoBtn.setText("Atras");
        atrasMstrrCrrtoBtn.setBorder(null);
        atrasMstrrCrrtoBtn.setBorderPainted(false);
        atrasMstrrCrrtoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasMstrrCrrtoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                atrasMstrrCrrtoBtnMouseExited(evt);
            }
        });
        atrasMstrrCrrtoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasMstrrCrrtoBtnActionPerformed(evt);
            }
        });
        mstrrCrrtoFondoPanel.add(atrasMstrrCrrtoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 70, 30));

        fondoMstrrCrrtoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo gris.jpg"))); // NOI18N
        fondoMstrrCrrtoLabel.setText("jLabel1");
        mstrrCrrtoFondoPanel.add(fondoMstrrCrrtoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        mstrrCarritoFrame.getContentPane().add(mstrrCrrtoFondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 416, 498));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo MenWear.png"))); // NOI18N
        logoLabel.setText("jLabel1");
        getContentPane().add(logoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, 180));

        tituloLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloLabel.setText("Bienvenido a MenWear");
        getContentPane().add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        catalogoBtn.setBackground(new java.awt.Color(51, 51, 51));
        catalogoBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        catalogoBtn.setForeground(new java.awt.Color(204, 204, 204));
        catalogoBtn.setText("Catalogo");
        catalogoBtn.setBorder(null);
        catalogoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catalogoBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catalogoBtnMouseExited(evt);
            }
        });
        catalogoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalogoBtnActionPerformed(evt);
            }
        });
        getContentPane().add(catalogoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 360, 40));

        menuTituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        menuTituloLabel.setForeground(new java.awt.Color(0, 0, 0));
        menuTituloLabel.setText("Menu");
        getContentPane().add(menuTituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        mostrarBtn.setBackground(new java.awt.Color(51, 51, 51));
        mostrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mostrarBtn.setForeground(new java.awt.Color(204, 204, 204));
        mostrarBtn.setText("Mostrar carrito");
        mostrarBtn.setBorder(null);
        mostrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostrarBtnMouseExited(evt);
            }
        });
        mostrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 360, 40));

        eliminarBtn.setBackground(new java.awt.Color(52, 51, 51));
        eliminarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminarBtn.setForeground(new java.awt.Color(204, 204, 204));
        eliminarBtn.setText("Eliminar del carrito");
        eliminarBtn.setBorder(null);
        eliminarBtn.setBorderPainted(false);
        eliminarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminarBtnMouseExited(evt);
            }
        });
        getContentPane().add(eliminarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 360, 40));

        comprarBtn.setBackground(new java.awt.Color(51, 51, 51));
        comprarBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        comprarBtn.setForeground(new java.awt.Color(204, 204, 204));
        comprarBtn.setText("Comprar");
        comprarBtn.setBorder(null);
        comprarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                comprarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                comprarBtnMouseExited(evt);
            }
        });
        getContentPane().add(comprarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 360, 40));

        salirBtn.setBackground(new java.awt.Color(51, 51, 51));
        salirBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        salirBtn.setForeground(new java.awt.Color(204, 204, 204));
        salirBtn.setText("Salir");
        salirBtn.setBorder(null);
        salirBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirBtnMouseExited(evt);
            }
        });
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        getContentPane().add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 360, 40));

        fondoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo gris.jpg"))); // NOI18N
        getContentPane().add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catalogoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoBtnMouseEntered
        catalogoBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_catalogoBtnMouseEntered

    private void catalogoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogoBtnMouseExited
        catalogoBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_catalogoBtnMouseExited

    private void mostrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseEntered
        mostrarBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_mostrarBtnMouseEntered

    private void mostrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarBtnMouseExited
        mostrarBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_mostrarBtnMouseExited

    private void eliminarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnMouseEntered
        eliminarBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_eliminarBtnMouseEntered

    private void eliminarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarBtnMouseExited
        eliminarBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_eliminarBtnMouseExited

    private void comprarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarBtnMouseEntered
        comprarBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_comprarBtnMouseEntered

    private void comprarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarBtnMouseExited
        comprarBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_comprarBtnMouseExited

    private void salirBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseEntered
        salirBtn.setBackground(Color.decode("#7B0D0D"));
    }//GEN-LAST:event_salirBtnMouseEntered

    private void salirBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirBtnMouseExited
        salirBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_salirBtnMouseExited

    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.out.println("Gracias por visitarnos :D");
        System.exit(0); // esta instruccion sale del todo el programa cuando se presiona el boton salir en el menu de la tienda.
    }//GEN-LAST:event_salirBtnActionPerformed

    private void catalogoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalogoBtnActionPerformed
        setVisible(false);
        catalogoFrame.pack();
        catalogoFrame.setVisible(true);
        catalogoFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_catalogoBtnActionPerformed

    private void camisasCtlgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camisasCtlgBtnMouseEntered
        camisasCtlgBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_camisasCtlgBtnMouseEntered

    private void camisasCtlgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_camisasCtlgBtnMouseExited
        camisasCtlgBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_camisasCtlgBtnMouseExited

    private void pantalonesCtlgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantalonesCtlgBtnMouseEntered
        pantalonesCtlgBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_pantalonesCtlgBtnMouseEntered

    private void pantalonesCtlgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantalonesCtlgBtnMouseExited
        pantalonesCtlgBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_pantalonesCtlgBtnMouseExited

    private void gorrasCtlgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gorrasCtlgBtnMouseEntered
        gorrasCtlgBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_gorrasCtlgBtnMouseEntered

    private void gorrasCtlgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gorrasCtlgBtnMouseExited
        gorrasCtlgBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_gorrasCtlgBtnMouseExited

    private void sueteresCtlgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sueteresCtlgBtnMouseEntered
        sueteresCtlgBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_sueteresCtlgBtnMouseEntered

    private void sueteresCtlgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sueteresCtlgBtnMouseExited
        sueteresCtlgBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_sueteresCtlgBtnMouseExited

    private void zapatosCtlgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zapatosCtlgBtnMouseEntered
        zapatosCtlgBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_zapatosCtlgBtnMouseEntered

    private void zapatosCtlgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zapatosCtlgBtnMouseExited
        zapatosCtlgBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_zapatosCtlgBtnMouseExited

    private void calzonetasCtlgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calzonetasCtlgBtnMouseEntered
        calzonetasCtlgBtn.setBackground(Color.BLACK);
    }//GEN-LAST:event_calzonetasCtlgBtnMouseEntered

    private void calzonetasCtlgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calzonetasCtlgBtnMouseExited
        calzonetasCtlgBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_calzonetasCtlgBtnMouseExited

    private void atrasCtlgBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasCtlgBtnMouseEntered
        atrasCtlgBtn.setBackground(Color.decode("#480000"));
    }//GEN-LAST:event_atrasCtlgBtnMouseEntered

    private void atrasCtlgBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasCtlgBtnMouseExited
        atrasCtlgBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_atrasCtlgBtnMouseExited

    private void atrasCtlgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasCtlgBtnActionPerformed
        catalogoFrame.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_atrasCtlgBtnActionPerformed

    private void atrasCmsasBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasCmsasBtnMouseEntered
        atrasCmsasBtn.setBackground(Color.decode("#C85D5D"));
    }//GEN-LAST:event_atrasCmsasBtnMouseEntered

    private void atrasCmsasBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasCmsasBtnMouseExited
        atrasCmsasBtn.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_atrasCmsasBtnMouseExited

    private void atrasCmsasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasCmsasBtnActionPerformed
        camisasCtlgFrame.setVisible(false);
        catalogoFrame.setVisible(true);
    }//GEN-LAST:event_atrasCmsasBtnActionPerformed

    private void camisasCtlgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camisasCtlgBtnActionPerformed
        catalogoFrame.setVisible(false);
        camisasCtlgFrame.pack();
        camisasCtlgFrame.setVisible(true);
        camisasCtlgFrame.setLocationRelativeTo(null);
    }//GEN-LAST:event_camisasCtlgBtnActionPerformed

    private void camisaMngCrtaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_camisaMngCrtaBtnActionPerformed
        // Talvez hacer un do while hasta que la cantidad total sea 0, usar joption para conseguir el numero que ingreso e ir restando.
        int precio = 600; int cantidadTotal = 10; String nombre = "Camisa"; String tipo = "Camisa manga corta";
        camisas.add(TiendaDeRopa.opcionCant(nombre,tipo,cantidadTotal,precio));
        /*for (int i = 0; i < camisas.size(); i++) {
            System.out.println((i + 1) + "\n" + camisas.get(i));
        }*/
    }//GEN-LAST:event_camisaMngCrtaBtnActionPerformed

    private void mostrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarBtnActionPerformed
        setVisible(false);
        mstrrCarritoFrame.pack();
        mstrrCarritoFrame.setVisible(true);
        mstrrCarritoFrame.setLocationRelativeTo(null);
        mostrarCarritoTxtArea.setText("");
        // todo esto mostrara lo que tienes dentro de tu carrito, validado todo
        int opcion = 0;
        do {
            opcion = Integer.parseInt(JOptionPane.showInputDialog(null, "Que cosas del tu carrito deseas ver\n0) Todo lo que agregue\n1) Camisas\n2) Pantalones\n3) Gorras\n4) Sueteres\n5) Zapatos\n6) Calzonetas\n7) Salir"));
            if (opcion < 0 || opcion > 7){
                JOptionPane.showMessageDialog(null, "No ingresaste un valor valido, Intenta de nuevo");
            } else {
                if (opcion == 0 && camisas.isEmpty() && pantalones.isEmpty() && gorras.isEmpty() && sueteres.isEmpty() && zapatos.isEmpty() && calzonetas.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No haz agregado nada al carrito");
                } else if (opcion == 0){
                    for (int i = 0; i < camisas.size(); i++) {
                        mostrarCarritoTxtArea.append("\n-------Camisa " + (i+1) +"---------" + camisas.get(i));
                    } 
                    for (int i = 0; i < pantalones.size(); i++) {
                        mostrarCarritoTxtArea.append("\n-------Pantalon " + (i+1) +"---------" + pantalones.get(i));
                    }
                    for (int i = 0; i < gorras.size(); i++) {
                        mostrarCarritoTxtArea.append("\n-------Gorra " + (i+1) +"---------" + gorras.get(i));
                    }
                    for (int i = 0; i < sueteres.size(); i++) {
                        mostrarCarritoTxtArea.append("\n-------Sueter " + (i+1) +"---------" + sueteres.get(i));
                    }
                    for (int i = 0; i < calzonetas.size(); i++) {
                        mostrarCarritoTxtArea.append("\n-------Calzoneta " + (i+1) +"---------" + calzonetas.get(i));
                    }
                    break;
                }else if (opcion == 1 && camisas.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No tienes nada agregado en camisas");
                } else if (opcion == 2 && pantalones.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No tienes nada agregado en pantalones");
                } else if (opcion == 3 && gorras.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No tienes nada agregado en gorras");
                } else if (opcion == 4 && sueteres.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No tienes nada agregado en sueteres");
                } else if (opcion == 5 && zapatos.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No tienes nada agregado en zapatos");
                } else if (opcion == 6 && calzonetas.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No tienes nada agregado en calzonetas");
                } else {
                    switch (opcion){
                        case 1:
                            for (int i = 0; i < camisas.size(); i++) {
                                mostrarCarritoTxtArea.append("\n-------Camisa " + (i+1) +"---------" + camisas.get(i));
                            } 
                            break;
                        case 2:
                            for (int i = 0; i < pantalones.size(); i++) {
                                mostrarCarritoTxtArea.append("\n-------Pantalon " + (i+1) +"---------" + pantalones.get(i));
                            }
                            break;
                        case 3:
                            for (int i = 0; i < gorras.size(); i++) {
                                mostrarCarritoTxtArea.append("\n-------Gorra " + (i+1) +"---------" + gorras.get(i));
                            }
                            break;
                        case 4:
                            for (int i = 0; i < sueteres.size(); i++) {
                                mostrarCarritoTxtArea.append("\n-------Sueter " + (i+1) +"---------" + sueteres.get(i));
                            }
                            break;
                        case 5:
                            for (int i = 0; i < zapatos.size(); i++) {
                                mostrarCarritoTxtArea.append("\n-------Zapato " + (i+1) +"---------" + zapatos.get(i));
                            }
                            break;
                        case 6:
                            for (int i = 0; i < calzonetas.size(); i++) {
                                mostrarCarritoTxtArea.append("\n-------Calzoneta " + (i+1) +"---------" + calzonetas.get(i));
                            }
                            break;
                    }
                }
            }
        } while (opcion != 7);
    }//GEN-LAST:event_mostrarBtnActionPerformed

    private void atrasMstrrCrrtoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMstrrCrrtoBtnMouseEntered
        atrasMstrrCrrtoBtn.setBackground(Color.decode("#480000"));
    }//GEN-LAST:event_atrasMstrrCrrtoBtnMouseEntered

    private void atrasMstrrCrrtoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMstrrCrrtoBtnMouseExited
        atrasMstrrCrrtoBtn.setBackground(Color.decode("#333333"));
    }//GEN-LAST:event_atrasMstrrCrrtoBtnMouseExited

    private void atrasMstrrCrrtoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasMstrrCrrtoBtnActionPerformed
        mstrrCarritoFrame.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_atrasMstrrCrrtoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenuTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenuTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasCmsasBtn;
    private javax.swing.JButton atrasCtlgBtn;
    private javax.swing.JButton atrasMstrrCrrtoBtn;
    private javax.swing.JButton calzonetasCtlgBtn;
    private javax.swing.JButton camisaMngCrtaBtn;
    private javax.swing.JButton camisaMngLrgBtn;
    private javax.swing.JButton camisasCtlgBtn;
    private javax.swing.JFrame camisasCtlgFrame;
    private javax.swing.JLabel camisasLabel;
    private javax.swing.JPanel camisasPanel;
    private javax.swing.JButton camisetaMngCrtaBtn;
    private javax.swing.JButton camisetaMngLrgBtn;
    private javax.swing.JButton catalogoBtn;
    private javax.swing.JFrame catalogoFrame;
    private javax.swing.JLabel catalogoLabel;
    private javax.swing.JPanel catalogoPanel;
    private javax.swing.JButton comprarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JLabel fondoCmsasLabel;
    private javax.swing.JLabel fondoCtlgLabel;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel fondoMstrrCrrtoLabel;
    private javax.swing.JButton gorrasCtlgBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel menuTituloLabel;
    private javax.swing.JButton mostrarBtn;
    private javax.swing.JTextArea mostrarCarritoTxtArea;
    private javax.swing.JFrame mstrrCarritoFrame;
    private javax.swing.JPanel mstrrCrrtoFondoPanel;
    private javax.swing.JPanel mstrrCrrtoPanel;
    private javax.swing.JButton pantalonesCtlgBtn;
    private javax.swing.JButton salirBtn;
    private javax.swing.JButton sueteresCtlgBtn;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JButton zapatosCtlgBtn;
    // End of variables declaration//GEN-END:variables
}
